[theme]
base = "light"
primaryColor = "#EF4444"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8FAFC"
textColor = "#0F172A"
font = "sans serif"

[server]
headless = true
enableCORS = false

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = true
